AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Photo Album Lambdas
Resources:
  Bucket1:
    Type: 'AWS::S3::Bucket'
    BucketName: new-pa-b2
    PublicAccessBlockConfiguration:
      BlockPublicAcls: FALSE
      BlockPublicPolicy: FALSE
      IgnorePublicAcls: FALSE
      RestrictPublicBuckets: FALSE
    CorsConfiguration:
      CorsRules:
        - - AllowedHeaders: "*"
            AllowedMethods: "POST,GET,DELETE,PUT,HEAD"
            AllowedOrigins: "*"
            ExposedHeaders: "Content-Range,Content-Length,ETag"
            MaxAge: 3000
  Bucket1Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket1
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - '*'
            Effect: Allow
            Resource: !Sub
             - arn:aws:s3:::${PhotoBucket}/*
             - { PhotoBucket: !Ref Bucket1 }
            Principal: '*'
            Sid: PublicReadGetObject
  pasearchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: pa-search-photos-cp
      Handler: pa_search_photos.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: 'Lambda for searching photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::637817358320:role/service-role/pa-search-photos-role-1jccqcif'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      Environment:
        Variables:
          REGION: us-east-1
  paindexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: pa-index-photos-cp
      Handler: pa_index_photos.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: 'Lambda for indexing photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::637817358320:role/service-role/pa-index-photos-role-oc3577ez'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket: !Ref Bucket1
            Events:
              - 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: photos/
      Environment:
        Variables:
          REGION: us-east-1
  
          