AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Photo Album Lambdas
Resources:
  pasearchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: pa-search-photos-cp
      Handler: pa_search_photos.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: 'Lambda for searching photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::637817358320:role/service-role/pa-search-photos-role-1jccqcif'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      Environment:
        Variables:
          REGION: us-east-1
  paindexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: pa-index-photos-cp
      Handler: pa_index_photos.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: 'Lambda for indexing photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::637817358320:role/service-role/pa-index-photos-role-oc3577ez'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: photos/
      Environment:
        Variables:
          REGION: us-east-1
  Bucket1:
    Type: 'AWS::S3::Bucket'